import {Component} from 'react';
import CadacoDisc from './CadacoDisc';

const mockData = [
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 0,
    "walk": 0,
    "strikeout": 0,
    "average": ".---",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Alexander, Scott",
    "playerId": "518397",
    "firstName": "Scott",
    "lastName": "Alexander"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 0,
    "walk": 0,
    "strikeout": 0,
    "average": ".---",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Baez, Pedro",
    "playerId": "520980",
    "firstName": "Pedro",
    "lastName": "Baez"
},
{
    "dataFound": true,
    "homeRun": 5,
    "groundOut": 49,
    "flyOut": 66,
    "triple": 1,
    "single": 43,
    "double": 12,
    "atBats": 212,
    "walk": 23,
    "strikeout": 56,
    "average": ".203",
    "teamId": "119",
    "primaryPosition": "C",
    "name": "Barnes, Austin",
    "playerId": "605131",
    "firstName": "Austin",
    "lastName": "Barnes"
},
{
    "dataFound": true,
    "homeRun": 9,
    "groundOut": 83,
    "flyOut": 67,
    "triple": 1,
    "single": 66,
    "double": 19,
    "atBats": 249,
    "walk": 17,
    "strikeout": 33,
    "average": ".265",
    "teamId": "119",
    "primaryPosition": "1B",
    "name": "Beaty, Matt",
    "playerId": "607461",
    "firstName": "Matt",
    "lastName": "Beaty"
},
{
    "dataFound": true,
    "homeRun": 47,
    "groundOut": 104,
    "flyOut": 181,
    "triple": 3,
    "single": 170,
    "double": 34,
    "atBats": 558,
    "walk": 95,
    "strikeout": 108,
    "average": ".305",
    "teamId": "119",
    "primaryPosition": "RF",
    "name": "Bellinger, Cody",
    "playerId": "641355",
    "firstName": "Cody",
    "lastName": "Bellinger"
},
{
    "dataFound": true,
    "homeRun": 1,
    "groundOut": 18,
    "flyOut": 6,
    "triple": 0,
    "single": 5,
    "double": 0,
    "atBats": 59,
    "walk": 4,
    "strikeout": 33,
    "average": ".085",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Buehler, Walker",
    "playerId": "621111",
    "firstName": "Walker",
    "lastName": "Buehler"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 1,
    "walk": 0,
    "strikeout": 1,
    "average": ".000",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Chargois, JT",
    "playerId": "608638",
    "firstName": "JT",
    "lastName": "Chargois"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 1,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 1,
    "walk": 0,
    "strikeout": 0,
    "average": ".000",
    "teamId": "119",
    "primaryPosition": "C",
    "name": "d'Arnaud, Travis",
    "playerId": "518595",
    "firstName": "Travis",
    "lastName": "d'Arnaud"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 1,
    "flyOut": 0,
    "triple": 0,
    "single": 1,
    "double": 1,
    "atBats": 2,
    "walk": 0,
    "strikeout": 0,
    "average": ".500",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Ferguson, Caleb",
    "playerId": "657571",
    "firstName": "Caleb",
    "lastName": "Ferguson"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 1,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 2,
    "walk": 0,
    "strikeout": 1,
    "average": ".000",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Floro, Dylan",
    "playerId": "571670",
    "firstName": "Dylan",
    "lastName": "Floro"
},
{
    "dataFound": true,
    "homeRun": 11,
    "groundOut": 37,
    "flyOut": 30,
    "triple": 0,
    "single": 51,
    "double": 13,
    "atBats": 162,
    "walk": 23,
    "strikeout": 44,
    "average": ".315",
    "teamId": "119",
    "primaryPosition": "1B",
    "name": "Freese, David",
    "playerId": "501896",
    "firstName": "David",
    "lastName": "Freese"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 3,
    "flyOut": 3,
    "triple": 0,
    "single": 2,
    "double": 0,
    "atBats": 15,
    "walk": 0,
    "strikeout": 7,
    "average": ".133",
    "teamId": "119",
    "primaryPosition": "C",
    "name": "Gale, Rocky",
    "playerId": "502570",
    "firstName": "Rocky",
    "lastName": "Gale"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 1,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 2,
    "walk": 0,
    "strikeout": 1,
    "average": ".000",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Garcia, Yimi",
    "playerId": "554340",
    "firstName": "Yimi",
    "lastName": "Garcia"
},
{
    "dataFound": true,
    "homeRun": 3,
    "groundOut": 5,
    "flyOut": 12,
    "triple": 0,
    "single": 12,
    "double": 4,
    "atBats": 48,
    "walk": 5,
    "strikeout": 19,
    "average": ".250",
    "teamId": "119",
    "primaryPosition": "RF",
    "name": "Garlick, Kyle",
    "playerId": "664247",
    "firstName": "Kyle",
    "lastName": "Garlick"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 2,
    "flyOut": 4,
    "triple": 0,
    "single": 4,
    "double": 0,
    "atBats": 13,
    "walk": 0,
    "strikeout": 4,
    "average": ".308",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Gonsolin, Tony",
    "playerId": "664062",
    "firstName": "Tony",
    "lastName": "Gonsolin"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 6,
    "flyOut": 15,
    "triple": 0,
    "single": 5,
    "double": 1,
    "atBats": 36,
    "walk": 3,
    "strikeout": 10,
    "average": ".139",
    "teamId": "119",
    "primaryPosition": "3B",
    "name": "Gyorko, Jedd",
    "playerId": "576397",
    "firstName": "Jedd",
    "lastName": "Gyorko"
},
{
    "dataFound": true,
    "homeRun": 17,
    "groundOut": 86,
    "flyOut": 137,
    "triple": 1,
    "single": 98,
    "double": 19,
    "atBats": 414,
    "walk": 36,
    "strikeout": 97,
    "average": ".237",
    "teamId": "119",
    "primaryPosition": "2B",
    "name": "Hernandez, Enrique",
    "playerId": "571771",
    "firstName": "Enrique",
    "lastName": "Hernandez"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 7,
    "flyOut": 0,
    "triple": 0,
    "single": 3,
    "double": 1,
    "atBats": 18,
    "walk": 1,
    "strikeout": 9,
    "average": ".167",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Hill, Rich",
    "playerId": "448179",
    "firstName": "Rich",
    "lastName": "Hill"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 1,
    "walk": 0,
    "strikeout": 1,
    "average": ".000",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Jansen, Kenley",
    "playerId": "445276",
    "firstName": "Kenley",
    "lastName": "Jansen"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 1,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 2,
    "walk": 0,
    "strikeout": 2,
    "average": ".000",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Kelly, Joe",
    "playerId": "523260",
    "firstName": "Joe",
    "lastName": "Kelly"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 32,
    "flyOut": 11,
    "triple": 0,
    "single": 5,
    "double": 1,
    "atBats": 49,
    "walk": 1,
    "strikeout": 16,
    "average": ".102",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Kershaw, Clayton",
    "playerId": "477132",
    "firstName": "Clayton",
    "lastName": "Kershaw"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 0,
    "walk": 0,
    "strikeout": 0,
    "average": ".---",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Kolarek, Adam",
    "playerId": "592473",
    "firstName": "Adam",
    "lastName": "Kolarek"
},
{
    "dataFound": true,
    "homeRun": 2,
    "groundOut": 17,
    "flyOut": 16,
    "triple": 1,
    "single": 18,
    "double": 4,
    "atBats": 75,
    "walk": 7,
    "strikeout": 24,
    "average": ".240",
    "teamId": "119",
    "primaryPosition": "2B",
    "name": "Lux, Gavin",
    "playerId": "666158",
    "firstName": "Gavin",
    "lastName": "Lux"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 27,
    "flyOut": 9,
    "triple": 0,
    "single": 12,
    "double": 2,
    "atBats": 48,
    "walk": 0,
    "strikeout": 13,
    "average": ".250",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Maeda, Kenta",
    "playerId": "628317",
    "firstName": "Kenta",
    "lastName": "Maeda"
},
{
    "dataFound": true,
    "homeRun": 6,
    "groundOut": 60,
    "flyOut": 45,
    "triple": 0,
    "single": 46,
    "double": 5,
    "atBats": 209,
    "walk": 30,
    "strikeout": 60,
    "average": ".220",
    "teamId": "119",
    "primaryPosition": "C",
    "name": "Martin, Russell",
    "playerId": "431145",
    "firstName": "Russell",
    "lastName": "Martin"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 5,
    "flyOut": 1,
    "triple": 0,
    "single": 1,
    "double": 0,
    "atBats": 11,
    "walk": 0,
    "strikeout": 4,
    "average": ".091",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "May, Dustin",
    "playerId": "669160",
    "firstName": "Dustin",
    "lastName": "May"
},
{
    "dataFound": true,
    "homeRun": 35,
    "groundOut": 107,
    "flyOut": 113,
    "triple": 1,
    "single": 122,
    "double": 22,
    "atBats": 487,
    "walk": 90,
    "strikeout": 149,
    "average": ".251",
    "teamId": "119",
    "primaryPosition": "1B",
    "name": "Muncy, Max",
    "playerId": "571970",
    "firstName": "Max",
    "lastName": "Muncy"
},
{
    "dataFound": true,
    "homeRun": 2,
    "groundOut": 14,
    "flyOut": 9,
    "triple": 0,
    "single": 14,
    "double": 1,
    "atBats": 54,
    "walk": 3,
    "strikeout": 17,
    "average": ".259",
    "teamId": "119",
    "primaryPosition": "2B",
    "name": "Negron, Kristopher",
    "playerId": "502117",
    "firstName": "Kristopher",
    "lastName": "Negron"
},
{
    "dataFound": true,
    "homeRun": 36,
    "groundOut": 110,
    "flyOut": 119,
    "triple": 3,
    "single": 112,
    "double": 16,
    "atBats": 450,
    "walk": 50,
    "strikeout": 111,
    "average": ".249",
    "teamId": "119",
    "primaryPosition": "LF",
    "name": "Pederson, Joc",
    "playerId": "592626",
    "firstName": "Joc",
    "lastName": "Pederson"
},
{
    "dataFound": true,
    "homeRun": 15,
    "groundOut": 79,
    "flyOut": 77,
    "triple": 1,
    "single": 82,
    "double": 15,
    "atBats": 308,
    "walk": 23,
    "strikeout": 74,
    "average": ".266",
    "teamId": "119",
    "primaryPosition": "CF",
    "name": "Pollock, AJ",
    "playerId": "572041",
    "firstName": "AJ",
    "lastName": "Pollock"
},
{
    "dataFound": true,
    "homeRun": 4,
    "groundOut": 10,
    "flyOut": 3,
    "triple": 1,
    "single": 13,
    "double": 2,
    "atBats": 47,
    "walk": 9,
    "strikeout": 21,
    "average": ".277",
    "teamId": "119",
    "primaryPosition": "3B",
    "name": "Rios, Edwin",
    "playerId": "621458",
    "firstName": "Edwin",
    "lastName": "Rios"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 0,
    "walk": 0,
    "strikeout": 0,
    "average": ".---",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Rosscup, Zac",
    "playerId": "573127",
    "firstName": "Zac",
    "lastName": "Rosscup"
},
{
    "dataFound": true,
    "homeRun": 1,
    "groundOut": 26,
    "flyOut": 6,
    "triple": 0,
    "single": 8,
    "double": 1,
    "atBats": 51,
    "walk": 4,
    "strikeout": 23,
    "average": ".157",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Ryu, Hyun Jin",
    "playerId": "547943",
    "firstName": "Hyun Jin",
    "lastName": "Ryu"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 1,
    "flyOut": 1,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 3,
    "walk": 0,
    "strikeout": 1,
    "average": ".000",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Sadler, Casey",
    "playerId": "594987",
    "firstName": "Casey",
    "lastName": "Sadler"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 1,
    "flyOut": 0,
    "triple": 0,
    "single": 1,
    "double": 0,
    "atBats": 2,
    "walk": 0,
    "strikeout": 0,
    "average": ".500",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Santana, Dennis",
    "playerId": "642701",
    "firstName": "Dennis",
    "lastName": "Santana"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 0,
    "walk": 0,
    "strikeout": 0,
    "average": ".---",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Sborz, Josh",
    "playerId": "622250",
    "firstName": "Josh",
    "lastName": "Sborz"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 0,
    "triple": 0,
    "single": 0,
    "double": 0,
    "atBats": 0,
    "walk": 0,
    "strikeout": 0,
    "average": ".---",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Schultz, Jaime",
    "playerId": "621289",
    "firstName": "Jaime",
    "lastName": "Schultz"
},
{
    "dataFound": true,
    "homeRun": 19,
    "groundOut": 118,
    "flyOut": 144,
    "triple": 1,
    "single": 133,
    "double": 44,
    "atBats": 489,
    "walk": 44,
    "strikeout": 98,
    "average": ".272",
    "teamId": "119",
    "primaryPosition": "SS",
    "name": "Seager, Corey",
    "playerId": "608369",
    "firstName": "Corey",
    "lastName": "Seager"
},
{
    "dataFound": true,
    "homeRun": 15,
    "groundOut": 25,
    "flyOut": 53,
    "triple": 0,
    "single": 43,
    "double": 9,
    "atBats": 170,
    "walk": 18,
    "strikeout": 52,
    "average": ".253",
    "teamId": "119",
    "primaryPosition": "C",
    "name": "Smith, Will",
    "playerId": "669257",
    "firstName": "Will",
    "lastName": "Smith"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 0,
    "flyOut": 2,
    "triple": 0,
    "single": 1,
    "double": 1,
    "atBats": 3,
    "walk": 0,
    "strikeout": 0,
    "average": ".333",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Stewart, Brock",
    "playerId": "592779",
    "firstName": "Brock",
    "lastName": "Stewart"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 11,
    "flyOut": 1,
    "triple": 0,
    "single": 3,
    "double": 0,
    "atBats": 20,
    "walk": 2,
    "strikeout": 7,
    "average": ".150",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Stripling, Ross",
    "playerId": "548389",
    "firstName": "Ross",
    "lastName": "Stripling"
},
{
    "dataFound": true,
    "homeRun": 12,
    "groundOut": 75,
    "flyOut": 87,
    "triple": 4,
    "single": 96,
    "double": 29,
    "atBats": 366,
    "walk": 37,
    "strikeout": 115,
    "average": ".262",
    "teamId": "119",
    "primaryPosition": "LF",
    "name": "Taylor, Chris",
    "playerId": "621035",
    "firstName": "Chris",
    "lastName": "Taylor"
},
{
    "dataFound": true,
    "homeRun": 27,
    "groundOut": 97,
    "flyOut": 160,
    "triple": 0,
    "single": 139,
    "double": 24,
    "atBats": 479,
    "walk": 51,
    "strikeout": 88,
    "average": ".290",
    "teamId": "119",
    "primaryPosition": "3B",
    "name": "Turner, Justin",
    "playerId": "457759",
    "firstName": "Justin",
    "lastName": "Turner"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 9,
    "flyOut": 1,
    "triple": 0,
    "single": 3,
    "double": 0,
    "atBats": 12,
    "walk": 1,
    "strikeout": 4,
    "average": ".250",
    "teamId": "119",
    "primaryPosition": "P",
    "name": "Urias, Julio",
    "playerId": "628711",
    "firstName": "Julio",
    "lastName": "Urias"
},
{
    "dataFound": true,
    "homeRun": 12,
    "groundOut": 111,
    "flyOut": 88,
    "triple": 2,
    "single": 101,
    "double": 22,
    "atBats": 343,
    "walk": 26,
    "strikeout": 49,
    "average": ".294",
    "teamId": "119",
    "primaryPosition": "CF",
    "name": "Verdugo, Alex",
    "playerId": "657077",
    "firstName": "Alex",
    "lastName": "Verdugo"
},
{
    "dataFound": true,
    "homeRun": 0,
    "groundOut": 10,
    "flyOut": 7,
    "triple": 0,
    "single": 1,
    "double": 0,
    "atBats": 22,
    "walk": 4,
    "strikeout": 4,
    "average": ".045",
    "teamId": "119",
    "primaryPosition": "1B",
    "name": "White, Tyler",
    "playerId": "643603",
    "firstName": "Tyler",
    "lastName": "White"
}
];

function renderDiscs(playerData) {
    const playerDiscs = playerData.map((playerData) => 
        <CadacoDisc playerData={playerData}/>)
    
    return playerDiscs;
}

export default class CadacoDiscs extends Component {
    constructor(props) {
      super(props);
      this.state = { };
    }
  
    render() {
      return (
        <ul>{renderDiscs(mockData)}</ul>
      );
    }
  }